### ISSUE TITLE
last published yaks reference is 0.14.3 although yaks 0.15.1 has been released

### ISSUE THREAD

**Issue by apupier** [citrusframework/citrus-website#18]
https://citrusframework.org/yaks/reference/html/index.html

![image](https://github.com/citrusframework/citrus-website/assets/1105127/d588fef6-1278-4e74-95a0-fde1186d9069)

**Comment by apupier** [comment]
sounds like th epublishing is done through this GitHub Action https://github.com/citrusframework/yaks/actions/runs/4383403735 , last obe is 5 months old, so correspondngto March relase of 0.14.3. https://github.com/citrusframework/yaks/releases/tag/v0.14.3
0.15.1 was released in May https://github.com/citrusframework/yaks/releases/tag/v0.15.1
it seems that th eprocess must be triggered manually given it is marked triggered bya user:
![image](https://github.com/citrusframework/citrus-website/assets/1105127/3a4f9aa5-6da3-4253-bbe4-0f361af33d4c)

@christophd Can you trigger the build for 0.15.1 please?

**Comment by christophd** [comment]
@apupier many thanks - I am going to hit that release button ...

**Comment by christophd** [comment]
should be fixed now. thanks again @apupier
