### ISSUE TITLE
PDF links from citrusframework.org come back as 404

### ISSUE THREAD

**Issue by lebuitrago** [citrusframework/citrus-website#3]
**Citrus Version**
citrusframework.org linking issue

**Question**
There is an issue with linking PDF files from within the main site. I'm getting back a 404 when clicking on the link mentioned below.

**What I've tried so far**
N/A

**Additional information**
Link to PDF reference not working:
http://citrusframework.org/reference/pdf/citrus-reference-2.7.8.pdf

**Comment by svettwer** [comment]
Thx for the hint! :+1:
